name: Testing

on: [push, pull_request]
  
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.8", "3.9"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/setup.py'
    - name: Install dependencies
      run: |
        pip install -e .
    - name: pytest
      run: |
        pytest

  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && needs.build.result == 'success'
    permissions:
      # For pypi trusted publishing
      id-token: write
    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build and upload dist
        run: |
          pip install build
          python -m build

      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
          verbose: true        
